name: Deploy to hetzner over wireguard

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'

    - name: Install npm dependencies
      run: npm install

    - name: Run build task
      run: npm run build 

    - name: Set up WireGuard
      uses: egor-tensin/setup-wireguard@v1
      with:
        endpoint: '${{ secrets.TUNNEL_ENDPOINT }}'
        endpoint_public_key: '${{ secrets.TUNNEL_ENDPOINT_PUBLIC_KEY }}'
        ips: '${{ secrets.TUNNEL_IPS }}'
        allowed_ips: '${{ secrets.TUNNEL_ALLOWED_IPS }}'
        private_key: '${{ secrets.TUNNEL_PRIVATE_KEY }}'
        preshared_key: '${{ secrets.TUNNEL_PRESHARED_KEY }}'

    - name: Deploy to Production
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        SCRIPT_AFTER: |
          cd ${{ secrets.REMOTE_TARGET }}
          npm install
          pm2 startOrReload ecosystem.config.js
          pm2 save